---
- name: web servers running
  hosts: n1
  become: yes

  tasks:
  - name: Ensure git installed
    yum:
      name: git
      state: installed
  - name: Ensure git is updated
    git: 
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html/
...
