
---
- name: Running multiple web servers in single instance
  hosts: n3
  become: yes

  tasks:
  - name: Ensure apache is installed
    yum: 
      name: httpd
      state: installed
  - name: Ensure apache is started
    service: 
      name: httpd
      state: started
  - name: Ensure apache is enabled
    service:
      name: httpd
      enabled: yes
  
  - name: Ensure selinux is in permissive mode
    selinux:
      policy: targeted
      state: permissive
  - name: Ensure httpd.conf file is copied or not
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf
  - name: Ensure git is installed
    yum:
      name: git
      state: installed

  - name: Ensure getting url for ecomm website
    git: 
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html/
  - name: Ensure getting url for food website
    git: 
      repo: https://github.com/ravi2krishna/food.git
      dest: /var/www/html/
  
